--- 
- hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Add docker repository key
    apt_key:
      keyserver: hkp://p80.pool.sks-keyservers.net:80
      id: 58118E89F3A912897C070ADBF76221572C52609D

  - name: Add docker repository
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
      filename: docker

  - name: Install docker-engine package
    apt:
      name: docker-engine

  - name: Add ubuntu user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes 
...
