--- 
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:
  - name: Update apt repository info
    apt: update_cache=yes

  - name: Install apt-transport-https package
    apt: name=apt-transport-https state=installed

  - name: Add repository key
    apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

  - name: Add repository info to docker.list
    shell: sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list'

  - name: Update apt repository info for the second time
    apt: update_cache=yes

  - name: Remove lxc-docker package if it exists
    apt: name=apparmor state=absent purge=yes

  - name: Install linux-image-extra package
    shell: apt-get install -y linux-image-extra-$(uname -r)

  - name: Install apparmor package
    apt: name=apparmor state=installed

  - name: Install docker-engine package
    apt: name=docker-engine state=installed

  - name: Add ubuntu user to docker group
    action: user name=ubuntu groups="docker" append=yes 
...
