docker_gpg_key_url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
docker_repo_url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/docker-ce.repo
docker_repo: /etc/yum.repos.d/docker-ce.repo
