---
- name: Add docker gpg key
  rpm_key:
    key: "{{ docker_gpg_key_url }}"

- name: Add stable docker repo
  get_url:
    url: "{{ docker_repo_url }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Update cache and install docker
  yum:
    name: docker-ce
    state: latest
    update_cache: yes
...
