---
- name: Enable and start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add {{ username }} user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
...
